(use-modules ((guix licenses) #:prefix license:)
             (gnu packages autotools)
             (gnu packages glib)
             (gnu packages gtk)
             (gnu packages guile)
             (gnu packages pkg-config)
             (gnu packages qt)
             (guix build-system gnu)
             (guix git-download)
             (guix utils)
             (nongnu packages qt)
             (guix packages))

(define-public giqt
  (let ((commit "8af4618124f707558a1e00b1b7dbef044e8c4311"))
    (package (name "giqt")
             (version "0.0.1-alpha")
             (source (origin (method git-fetch)
                             (uri (git-reference (url "https://github.com/mrosset/giqt.git")
                                                 (commit commit)))
                             (file-name (git-file-name name version))
                             (sha256 (base32 "03vmsdfg3yb4ns9flv2vdb903iyavzcvn641jkpcnl10hisii7jh"))))
             (build-system gnu-build-system)
             (native-inputs `(("autoconf" ,autoconf)
                              ("automake" ,automake)
                              ("pkg-config" ,pkg-config)
                              ("libtool" ,libtool)
                              ("guile" ,guile-2.2)))
             (inputs `(("glib" ,glib)
                       ("gobject-introspection" ,gobject-introspection)
                       ("gtk+" ,gtk+)
                       ("qtbase" ,qtbase)
                       ("qtdeclarative" ,qtdeclarative)
                       ("qtwebchannel" ,qtwebchannel)
                       ("qtwebengine" ,qtwebengine)))
             (synopsis "GObject bindings for QT")
             (description "GIQT allows creating QT programs with the same interfaces as GTK")
             (home-page "https://github.com/mrosset/giqt")
             (license license:gpl3+))))

giqt
