(use-modules ((guix licenses) #:prefix license:)
             (gnu packages autotools)
             (gnu packages base)
             (gnu packages compression)
             (gnu packages glib)
             (gnu packages gtk)
             (gnu packages guile)
             (gnu packages pkg-config)
             (gnu packages qt)
             (guix build-system gnu)
             (guix build-system trivial)
             (guix git-download)
             (guix utils)
             (guix download)
             (nongnu packages qt)
             (guix packages))

(define-public via-qt-stack
  (package (name "via-qt-stack")
           (version "x86_64-via-linux-gnu")
           (source (origin (method url-fetch)
                           (uri "https://github.com/mrosset/giqt/releases/download/via-qt-stack/via-qt-stack.tar.xz")
                           (sha256 (base32 "1qjraym09szbqnmf15zx38a8hdw2dlpqdlw0w4w09wg2024q945w"))))
           (build-system gnu-build-system)
           (arguments
            `(#:phases (modify-phases %standard-phases
                         (delete 'configure)
                         (delete 'patch-source-shebangs)
                         (delete 'check)
                         (delete 'patch-generated-file-shebangs)
                         (delete 'patch-usr-bin-file)
                         (delete 'build)
                         (replace 'install
                           (lambda* (#:key outputs #:allow-other-keys)
                             (copy-recursively "../opt" (string-append (assoc-ref outputs "out")))
                             #t)))))
           (native-search-paths
            (list (search-path-specification
                   (file-type 'directory)
                   (separator ":")
                   (variable "PATH")
                   (files '("via/bin")))
                  ))
           (home-page "https://github.com/mrosset/giqt/releases/tag/via-qt-stack")
           (synopsis "via qt binary distribution")
           (description "via qt binary distribution")
           (license (list license:gpl3+))))

(define-public giqt
  (let ((commit "8af4618124f707558a1e00b1b7dbef044e8c4311"))
    (package (name "giqt")
             (version "0.0.1-alpha")
             (source (origin (method git-fetch)
                             (uri (git-reference (url "https://github.com/mrosset/giqt.git")
                                                 (commit commit)))
                             (file-name (git-file-name name version))
                             (sha256 (base32 "03vmsdfg3yb4ns9flv2vdb903iyavzcvn641jkpcnl10hisii7jh"))))
             (build-system gnu-build-system)
             (native-inputs `(("autoconf" ,autoconf)
                              ("automake" ,automake)
                              ("pkg-config" ,pkg-config)
                              ("libtool" ,libtool)
                              ("guile" ,guile-2.2)))
             (inputs `(("via-qt-stack" ,via-qt-stack)))
             (synopsis "GObject bindings for QT")
             (description "GIQT allows creating QT programs with the same interfaces as GTK")
             (home-page "https://github.com/mrosset/giqt")
             (license license:gpl3+))))

via-qt-stack
